# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export distIUPAC
#' @author Kristian K Ullrich
distIUPAC <- function(myvector) {
  .Call('_distIUPAC_distIUPAC', PACKAGE = 'distIUPAC', myvector)
}

#' @export distIUPACmatrix
#' @author Kristian K Ullrich
distIUPACmatrix <- function(myvector, scoreMatrix) {
  .Call('_distIUPAC_distIUPACmatrix', PACKAGE = 'distIUPAC', myvector, scoreMatrix)
}

