# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @useDynLib distIUPAC, .registration = TRUE
#' @import Rcpp
#' @export distIUPAC
#' @author Kristian K Ullrich
distIUPAC <- function(dnavector) {
    .Call(`_distIUPAC_distIUPAC`, dnavector)
}

#' @useDynLib distIUPAC, .registration = TRUE
#' @import Rcpp
#' @export distIUPACmatrix
#' @author Kristian K Ullrich
distIUPACmatrix <- function(dnavector, scoreMatrix) {
    .Call(`_distIUPAC_distIUPACmatrix`, dnavector, scoreMatrix)
}

#' @useDynLib distIUPAC, .registration = TRUE
#' @import Rcpp
#' @export pairwiseDeletion
#' @author Kristian K Ullrich
pairwiseDeletion <- function(dnavector) {
    .Call(`_distIUPAC_pairwiseDeletion`, dnavector)
}

#' @useDynLib distIUPAC, .registration = TRUE
#' @import Rcpp
#' @import RcppThread
#' @export rcpp_distIUPAC
#' @author Kristian K Ullrich
rcpp_distIUPAC <- function(dnavector, ncores = 1L) {
    .Call(`_distIUPAC_rcpp_distIUPAC`, dnavector, ncores)
}

#' @useDynLib distIUPAC, .registration = TRUE
#' @import Rcpp
#' @export rcpp_distIUPAC_ab
#' @author Kristian K Ullrich
rcpp_distIUPAC_ab <- function(a, b, nsites) {
    .Call(`_distIUPAC_rcpp_distIUPAC_ab`, a, b, nsites)
}

#' @useDynLib distIUPAC, .registration = TRUE
#' @import Rcpp
#' @import RcppThread
#' @export rcpp_distIUPACmatrix
#' @author Kristian K Ullrich
rcpp_distIUPACmatrix <- function(dnavector, scoreMatrix, ncores = 1L) {
    .Call(`_distIUPAC_rcpp_distIUPACmatrix`, dnavector, scoreMatrix, ncores)
}

#' @useDynLib distIUPAC, .registration = TRUE
#' @import Rcpp
#' @export rcpp_distIUPACmatrix_ab
#' @author Kristian K Ullrich
rcpp_distIUPACmatrix_ab <- function(a, b, scoreMatrix, nsites) {
    .Call(`_distIUPAC_rcpp_distIUPACmatrix_ab`, a, b, scoreMatrix, nsites)
}

#' @useDynLib distIUPAC, .registration = TRUE
#' @import Rcpp
#' @export rcpp_iupacString2diploidString
#' @author Kristian K Ullrich
rcpp_iupacString2diploidString <- function(a, nsites, name_a = "a1", name_b = "a2") {
    .Call(`_distIUPAC_rcpp_iupacString2diploidString`, a, nsites, name_a, name_b)
}

#' @useDynLib distIUPAC, .registration = TRUE
#' @import Rcpp
#' @export rcpp_iupacString_ab
#' @author Kristian K Ullrich
rcpp_iupacString_ab <- function(a, b, nsites, name = "iupacString") {
    .Call(`_distIUPAC_rcpp_iupacString_ab`, a, b, nsites, name)
}

#' @useDynLib distIUPAC, .registration = TRUE
#' @import Rcpp
#' @import RcppThread
#' @export rcpp_pairwiseDeletion
#' @author Kristian K Ullrich
rcpp_pairwiseDeletion <- function(dnavector, ncores = 1L) {
    .Call(`_distIUPAC_rcpp_pairwiseDeletion`, dnavector, ncores)
}

